export const products = [
  {
    id: 1,
    product_name: "Samsung",
    seller_name: "Mr Kazeem",
    description: "A samsung phone",
    phone: "7086030382",
    img: "/images/1.png",
  },
  {
    id: 2,
    product_name: "Iphone",
    seller_name: "Mr James",
    description: "An iPhone",
    phone: "7086030382",
    img: "/images/2.png",
  },
  {
    id: 3,
    product_name: "Infinix",
    seller_name: "Mr Gabriel",
    description: "A Infinix phone",
    phone: "7086030382",
    img: "/images/3.png",
  },
  {
    id: 4,
    product_name: "Gionee",
    seller_name: "Mr Samson",
    description: "A gionee phone",
    phone: "7086030382",
    img: "/images/5.png",
  },
  {
    id: 5,
    product_name: "Huawei",
    seller_name: "Mr Davidson",
    description: "A Huawei phone",
    phone: "7086030382",
    img: "/images/3.png",
  },
  {
    id: 6,
    product_name: "Nokia",
    seller_name: "Mr Joshua",
    description: "A Nokia phone",
    phone: "7086030382",
    img: "/images/2.png",
  },
  {
    id: 7,
    product_name: "iPhone Xr",
    seller_name: "Mr James",
    description: "iPhone xr",
    phone: "7086030382",
    img: "/images/1.png",
  },
  {
    id: 8,
    product_name: "Infinix Note",
    seller_name: "Mrs Blessing",
    description: "infinix note is a very nice phone",
    phone: "7086030382",
    img: "/images/5.png",
  },
  {
    id: 9,
    product_name: "Power Bank",
    seller_name: "Mr Temmy",
    description: "Nice power bank",
    phone: "7086030382",
    img: "/images/2.png",
  },
  {
    id: 10,
    product_name: "Laptop",
    seller_name: "Mr Lenity",
    description: "A beautiful toshiba laptop",
    phone: "7086030382",
    img: "/images/3.png",
  },
  {
    id: 11,
    product_name: "Hp Laptop",
    seller_name: "Mr Jefferson",
    description: "A beautiful toshiba laptop",
    phone: "7086030382",
    img: "/images/1.png",
  },
  {
    id: 12,
    product_name: "Headset",
    seller_name: "Mr Matthew",
    description: "A beautiful toshiba laptop",
    phone: "7086030382",
    img: "/images/3.png",
  },
];
