export const headerStyles = {
  container: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#490475",
    color: "#FCFCFC",
    boxShadow: "3px 6px 5px rgba(0, 0 , 0 , 0.6)",
    margin: "0 8px 15px 0",
  },
  logo: {
    padding: "5px",
    alignItems: "center",
    margin: "5px 5px",
    fontWeight: "bold",
    fontSize: "1.5rem",
    cursor: "pointer",
  },
  links: {
    display: "flex",
    flexDirection: "rows",
    alignItems: "center",
    margin: "8px 5px",
    textDecoration: "none",
    justifyContent: "center",
  },
  link: {
    alignItems: "center",
    textDecoration: "none",
    listStyle: "none",
    padding: "8px 10px",
    fontSize: "19px",
    cursor: "pointer",
  },
  actions: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 5px",
    margin: "8px 5px",
    gap: "1.5rem",
  },
};
